project:
  type: website

website:
  title: "prod-shiny-workshop"
  logo: images/shinybrain.png
  navbar:
    background: primary
    #foreground: '#00264d' # primary, secondary, success, danger, warning, info, light, dark
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: schedule.qmd
        text: Schedule
      - href: slides.qmd
        text: Slides

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    #css: styles.css
    toc: true

# https://quarto.org/docs/output-formats/html-themes.html#dark-mode

