baseURL: /
theme: hugo-apero
languageCode: en
title: Building Production-Grade Shiny Applications
author: Eric Nantz
copyright: ''
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
  - "(^|/)renv$"
  - "renv\\.lock$"
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: ''
  customheadingFontFamily: "Atkinson Hyperlegible"
  customtextFontFamily: Metropolis
  description: "Building Production-Grade Shiny Applications - Workshop at the 2022 rstudio::conf"
  favicon: /img/favicon.ico
  headingFontFamily: sans-serif
  logo: /img/shinydevseries_hex.png
  mainSections:
    - blog
    - project
    - talk
    - materials
  math:
    renderer: katex
  navallcaps: yes
  orgLocal: "rstudio::conf 2022"
  orgName: RStudio
  sharing_image: /img/rsconf_pic.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/arpodcast/prod-shiny-workshop
    - icon: rss
      icon_pack: fas
      url: /blog/index.xml
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  theme: sky
  twitter: theRcast
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: rpodcast/prod-shiny-workshop
    theme: boxy-light
    use_utterances: no
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
    - name: Code of Conduct
      title: Code of Conduct
      url: /code-of-conduct
      weight: 2
  header:
    - name: About
      title: About
      url: /about/
      weight: 1
    - name: Materials
      title: Materials
      url: /materials/
      weight: 2
privacy:
  disqus:
    disable: yes
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: yes
    simple: yes
  twitter:
    disable: yes
    enableDNT: yes
    simple: no
  vimeo:
    disable: yes
    enableDNT: yes
    simple: yes
  youtube:
    disable: yes
    privacyEnhanced: yes
security:
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_
      - "^BLOGDOWN_"
